modLoader = "javafml"
loaderVersion = "*"
license = "MPL-2.0"
issueTrackerURL="https://github.com/Qendolin/peaceful-nights/issues/new"

[[mods]]
modId = "peaceful_nights"
version = "${version}"
displayName = "${name}"
authors = "Qendolin"
description = "Prevent mobs from spawning on the surface during nights and thunderstorms"
logoFile = "assets/peaceful_nights/icon.png"
logoBlur = false

[[mixins]]
config = "peaceful_nights-common.mixins.json"

[[mixins]]
config = "peaceful_nights-neoforge.mixins.json"

